const dropArea = document.getElementById("drop-area");
const fileInput = document.getElementById("fileUpload");
const browseBtn = document.getElementById("browse-btn");
const preview = document.getElementById("preview");
const reportSection = document.getElementById("report-section");
const downloadBtn = document.getElementById("download-btn");

browseBtn.addEventListener("click", () => fileInput.click());

["dragenter", "dragover", "dragleave", "drop"].forEach(eventName => {
  dropArea.addEventListener(eventName, e => e.preventDefault());
  dropArea.addEventListener(eventName, e => e.stopPropagation());
});

dropArea.addEventListener("drop", handleDrop);
fileInput.addEventListener("change", handleFiles);

function handleDrop(e) {
  const files = e.dataTransfer.files;
  if (files.length) handleFile(files[0]);
}

function handleFiles(e) {
  const file = e.target.files[0];
  if (file) handleFile(file);
}

function handleFile(file) {
  if (!file.type.startsWith("image/")) {
    alert("Please upload an image file!");
    return;
  }

  const reader = new FileReader();
  reader.onload = e => {
    preview.innerHTML = `<img src="${e.target.result}" alt="Biopsy Image">`;
  };
  reader.readAsDataURL(file);

  simulateReportGeneration(file);
}

function simulateReportGeneration(file) {
  setTimeout(() => {
    const result = Math.random() > 0.3; // 70% healthy, 30% cancer detected
    const report = {
      patientId: "BC-" + Math.floor(Math.random() * 100000),
      fileName: file.name,
      diagnosis: result ? "Benign (Healthy Tissue)" : "Malignant Cells Detected ⚠️",
      confidence: result ? "97.8%" : "91.4%",
      date: new Date().toLocaleString(),
      note: result
        ? "No cancerous patterns detected in the biopsy image."
        : "Presence of malignant cell clusters detected. Recommend further clinical evaluation."
    };
    showReport(report);
  }, 1500);
}

function showReport(report) {
  document.getElementById("r-patient").textContent = report.patientId;
  document.getElementById("r-file").textContent = report.fileName;
  const diag = document.getElementById("r-diagnosis");
  diag.textContent = report.diagnosis;
  diag.classList.toggle("safe", report.diagnosis.includes("Benign"));
  document.getElementById("r-confidence").textContent = report.confidence;
  document.getElementById("r-date").textContent = report.date;
  document.getElementById("r-note").textContent = report.note;

  reportSection.classList.remove("hidden");

  downloadBtn.onclick = () => downloadReportAsPDF(report);
}

async function downloadReportAsPDF(report) {
  const { jsPDF } = window.jspdf;
  const doc = new jsPDF();

  doc.setFont("helvetica", "bold");
  doc.setFontSize(18);
  doc.text("Breast Cancer Biopsy Diagnostic Report", 20, 20);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Patient ID: ${report.patientId}`, 20, 40);
  doc.text(`Image Name: ${report.fileName}`, 20, 50);
  doc.text(`Diagnosis: ${report.diagnosis}`, 20, 60);
  doc.text(`Confidence: ${report.confidence}`, 20, 70);
  doc.text(`Analysis Date: ${report.date}`, 20, 80);

  doc.text("Doctor’s Note:", 20, 100);
  doc.text(report.note, 20, 110, { maxWidth: 170 });

  doc.setFontSize(10);
  doc.text("Generated by AI Diagnostic System", 20, 280);
  doc.text("© 2025 Breast Cancer Analysis Lab", 130, 280);

  doc.save(`Biopsy_Report_${report.patientId}.pdf`);
}
